version: '3'
services:
  adsb2dd:
    restart: always
    build:
      context: .
      network: host
    image: adsb2dd
    network_mode: host
    container_name: adsb2dd
    environment:
      - ALLOW_PRIVATE_NETWORKS=false
